export const ADD_EMPLOYER = "ADD_EMPLOYER";
export const CURRENT_EMPLOYER = "CURRENT_EMPLOYER";
export const LOAD_EMPLOYER = "LOAD_EMPLOYER";
export const FAIL_EMPLOYER = "FAIL_EMPLOYER";
export const DELETE_EMPLOYER = "DELETE_EMPLOYER";
export const FIND_EMPLOYER = "FIND_EMPLOYER";
export const MY_EMPLOYERS = "MY_EMPLOYERS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
